package com.opticalshop.utils

import com.opticalshop.data.model.Product
import com.opticalshop.data.remote.FirestoreService
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class DataSeeder @Inject constructor(
    private val firestoreService: FirestoreService
) {
    fun seedProducts() {
        val products = listOf(
            Product(
                id = "rb-aviator-01",
                name = "Aviator Classic",
                brand = "Ray-Ban",
                description = "Currently one of the most iconic sunglass models in the world, Ray-Ban Aviator Classic sunglasses were originally designed for U.S. aviators in 1937.",
                price = 163.0,
                originalPrice = 210.0,
                category = "Sunglasses",
                frameShape = "Aviator",
                frameMaterial = "Metal",
                frameColor = "Gold",
                lensType = "Polarized",
                gender = "Unisex",
                images = listOf("https://images.ray-ban.com/is/image/RayBan/805289602057__002.png"),
                stock = 25,
                rating = 4.8,
                reviewCount = 120,
                featured = true
            ),
            Product(
                id = "ok-holbrook-01",
                name = "Holbrook",
                brand = "Oakley",
                description = "Holbrook is a timeless, classic design fused with modern Oakley technology. Inspired by the screen heroes from the 1940s, 50s, and 60s.",
                price = 146.0,
                originalPrice = 180.0,
                category = "Sunglasses",
                frameShape = "Square",
                frameMaterial = "O Matter",
                frameColor = "Matte Black",
                lensType = "Prizm Sapphire",
                gender = "Men",
                images = listOf("https://assets.oakley.com/is/image/Oakley/888392100854__001.png"),
                stock = 15,
                rating = 4.7,
                reviewCount = 85
            ),
            Product(
                id = "pr-cinema-01",
                name = "Cinema Evolution",
                brand = "Prada",
                description = "Elegant and sophisticated, the Prada Cinema collection features a unique blend of metal and acetate with a vintage-inspired aesthetic.",
                price = 320.0,
                originalPrice = 400.0,
                category = "Luxury",
                frameShape = "Cat Eye",
                frameMaterial = "Acetate/Metal",
                frameColor = "Tortoise/Gold",
                lensType = "Gradient",
                gender = "Women",
                images = listOf("https://www.prada.com/content/dam/pradanux_products/S/SPR/53S/E1AB/F00A7/SPR53S_E1AB_F00A7_SLF.png"),
                stock = 10,
                rating = 4.9,
                reviewCount = 45,
                featured = true
            ),
            Product(
                id = "gc-web-01",
                name = "Aviator with Web",
                brand = "Gucci",
                description = "A classic aviator shape in gold metal, featuring the House Web on the temples. A nod to Gucci's equestrian roots.",
                price = 450.0,
                originalPrice = 550.0,
                category = "Luxury",
                frameShape = "Aviator",
                frameMaterial = "Metal",
                frameColor = "Gold",
                lensType = "Solid",
                gender = "Men",
                images = listOf("https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1544023508/544033_I3330_8005_001_100_0000_Light-Aviator-with-Web-details.jpg"),
                stock = 8,
                rating = 4.6,
                reviewCount = 30
            ),
            Product(
                id = "cr-hyperfit-01",
                name = "Hyperfit 10",
                brand = "Carrera",
                description = "The Carrera Hyperfit collection is designed for an active lifestyle, featuring specialized hinges that allow for a secure, custom fit.",
                price = 110.0,
                originalPrice = 140.0,
                category = "Sports",
                frameShape = "Rectangular",
                frameMaterial = "Polyamide",
                frameColor = "Blue",
                lensType = "Mirrored",
                gender = "Unisex",
                images = listOf("https://www.carreraworld.com/media/catalog/product/c/a/carrera_hyperfit_10_s_807_uz_01.png"),
                stock = 30,
                rating = 4.5,
                reviewCount = 60
            ),
            Product(
                id = "tf-fausto-01",
                name = "Fausto",
                brand = "Tom Ford",
                description = "A bold, thick-framed square shape that exudes masculine confidence. Hand-finished in Italy with premium acetate.",
                price = 395.0,
                originalPrice = 495.0,
                category = "Luxury",
                frameShape = "Square",
                frameMaterial = "Acetate",
                frameColor = "Black",
                lensType = "Dark Gray",
                gender = "Men",
                images = listOf("https://www.tomford.com/dw/image/v2/BCZV_PRD/on/demandware.static/-/Sites-master-catalog-tf/default/dw8e8e8e8e/images/hi-res/FT0711_01A_A.jpg"),
                stock = 12,
                rating = 4.8,
                reviewCount = 20
            ),
            Product(
                id = "rb-wayfarer-01",
                name = "Wayfarer Classic",
                brand = "Ray-Ban",
                description = "The Ray-Ban Original Wayfarer Classic is the most recognizable style in the history of sunglasses.",
                price = 163.0,
                originalPrice = 180.0,
                category = "Sunglasses",
                frameShape = "Square",
                frameMaterial = "Acetate",
                frameColor = "Black",
                lensType = "G-15 Green",
                gender = "Unisex",
                images = listOf("https://images.ray-ban.com/is/image/RayBan/805289126577__002.png"),
                stock = 40,
                rating = 4.9,
                reviewCount = 500,
                featured = true
            ),
            Product(
                id = "ok-frogskins-01",
                name = "Frogskins",
                brand = "Oakley",
                description = "In pop culture, it was a time like no other. Ronald Reagan was in the White House, The Terminator was in the box office and Run DMC was in certified gold.",
                price = 136.0,
                originalPrice = 160.0,
                category = "Sunglasses",
                frameShape = "Square",
                frameMaterial = "O Matter",
                frameColor = "Polished Black",
                lensType = "Prizm Gray",
                gender = "Unisex",
                images = listOf("https://assets.oakley.com/is/image/Oakley/888392100656__001.png"),
                stock = 20,
                rating = 4.6,
                reviewCount = 210
            ),
            Product(
                id = "tf-blueblock-01",
                name = "Blue Block Square",
                brand = "Tom Ford",
                description = "Sophisticated square optical frames featuring Blue Block lenses to reduce eye strain from digital screens.",
                price = 350.0,
                originalPrice = 420.0,
                category = "Computer",
                frameShape = "Square",
                frameMaterial = "Acetate",
                frameColor = "Shiny Black",
                lensType = "Blue Block",
                gender = "Unisex",
                images = listOf("https://www.tomford.com/dw/image/v2/BCZV_PRD/on/demandware.static/-/Sites-master-catalog-tf/default/dw123456/images/hi-res/FT5662_001_A.jpg"),
                stock = 18,
                rating = 4.7,
                reviewCount = 35
            ),
            Product(
                id = "rb-round-01",
                name = "Round Metal",
                brand = "Ray-Ban",
                description = "The Ray-Ban Round Metal sunglasses are totally retro. This look has been worn by legendary musicians and inspired by the 1960s counter-culture.",
                price = 154.0,
                originalPrice = 180.0,
                category = "Sunglasses",
                frameShape = "Round",
                frameMaterial = "Metal",
                frameColor = "Silver",
                lensType = "Solid Blue",
                gender = "Unisex",
                images = listOf("https://images.ray-ban.com/is/image/RayBan/805289439899__002.png"),
                stock = 22,
                rating = 4.8,
                reviewCount = 150
            ),
            Product(
                id = "ok-gascan-01",
                name = "Gascan",
                brand = "Oakley",
                description = "We swapped soft curves for straight edges and hard lines to sculpt our very first high-wrap lifestyle shades. The toric lens design became known as Gascan.",
                price = 112.0,
                originalPrice = 140.0,
                category = "Sports",
                frameShape = "Wrap",
                frameMaterial = "O Matter",
                frameColor = "Matte Black",
                lensType = "Black Iridium",
                gender = "Men",
                images = listOf("https://assets.oakley.com/is/image/Oakley/700285034731__001.png"),
                stock = 14,
                rating = 4.5,
                reviewCount = 95
            ),
            Product(
                id = "gc-round-01",
                name = "Round-Frame Metal",
                brand = "Gucci",
                description = "A thin gold metal frame with a double bridge. The temples are finished with the Gucci logo for a touch of elegance.",
                price = 420.0,
                originalPrice = 500.0,
                category = "Luxury",
                frameShape = "Round",
                frameMaterial = "Metal",
                frameColor = "Gold",
                lensType = "Pale Pink",
                gender = "Women",
                images = listOf("https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1550162104/561726_I3330_8131_001_100_0000_Light-Round-frame-metal-sunglasses.jpg"),
                stock = 6,
                rating = 4.9,
                reviewCount = 12
            ),
            Product(
                id = "cr-glory-01",
                name = "Glory Special Edition",
                brand = "Carrera",
                description = "Marking Carrera's 65th anniversary, the Glory sunglasses re-interpret the brand's archives with a modern twist.",
                price = 180.0,
                originalPrice = 220.0,
                category = "Sunglasses",
                frameShape = "Navigator",
                frameMaterial = "Metal",
                frameColor = "Matte Black/Gold",
                lensType = "Brown Gradient",
                gender = "Unisex",
                images = listOf("https://www.carreraworld.com/media/catalog/product/c/a/carrera_glory_2f7_uz_01.png"),
                stock = 20,
                rating = 4.7,
                reviewCount = 28
            ),
            Product(
                id = "tf-arnaud-01",
                name = "Arnaud",
                brand = "Tom Ford",
                description = "A classic pilot shape made entirely of acetate, featuring the signature 'T' logo at the hinge.",
                price = 415.0,
                originalPrice = 520.0,
                category = "Luxury",
                frameShape = "Pilot",
                frameMaterial = "Acetate",
                frameColor = "Dark Havana",
                lensType = "Green",
                gender = "Men",
                images = listOf("https://www.tomford.com/dw/image/v2/BCZV_PRD/on/demandware.static/-/Sites-master-catalog-tf/default/dw123/images/hi-res/FT0625_52N_A.jpg"),
                stock = 9,
                rating = 4.8,
                reviewCount = 15
            ),
            Product(
                id = "rb-clubmaster-01",
                name = "Clubmaster Classic",
                brand = "Ray-Ban",
                description = "Ray-Ban Clubmaster Classic sunglasses are retro and timeless. Inspired by the 50s.",
                price = 163.0,
                originalPrice = 190.0,
                category = "Sunglasses",
                frameShape = "Browline",
                frameMaterial = "Acetate/Metal",
                frameColor = "Black/Gold",
                lensType = "Green Classic G-15",
                gender = "Unisex",
                images = listOf("https://images.ray-ban.com/is/image/RayBan/805289653653__002.png"),
                stock = 35,
                rating = 4.9,
                reviewCount = 340,
                featured = true
            ),
            Product(
                id = "ok-jawbreaker-01",
                name = "Jawbreaker",
                brand = "Oakley",
                description = "Jawbreaker™ is the ultimate sport design - answering the demands of world-class athletes with a 40 year heritage of uncompromising excellence.",
                price = 220.0,
                originalPrice = 280.0,
                category = "Sports",
                frameShape = "Wrap",
                frameMaterial = "O Matter",
                frameColor = "White",
                lensType = "Prizm Road",
                gender = "Unisex",
                images = listOf("https://assets.oakley.com/is/image/Oakley/888392100458__001.png"),
                stock = 12,
                rating = 4.8,
                reviewCount = 115
            ),
            Product(
                id = "pr-linearossa-01",
                name = "Linea Rossa PS 01US",
                brand = "Prada",
                description = "Part of the active Linea Rossa collection, these sunglasses offer performance and high-fashion together.",
                price = 210.0,
                originalPrice = 260.0,
                category = "Sports",
                frameShape = "Rectangular",
                frameMaterial = "Sint",
                frameColor = "Black Rubber",
                lensType = "Tuning",
                gender = "Men",
                images = listOf("https://www.prada.com/content/dam/pradanux_products/S/SPS/01U/ETWK/F00A7/SPS01U_ETWK_F00A7_SLF.png"),
                stock = 15,
                rating = 4.6,
                reviewCount = 55
            ),
            Product(
                id = "tf-spector-01",
                name = "Spector",
                brand = "Tom Ford",
                description = "A modern navigator shape with a sleek double bridge and thin metal temples. Minimalist luxury at its finest.",
                price = 445.0,
                originalPrice = 540.0,
                category = "Luxury",
                frameShape = "Navigator",
                frameMaterial = "Metal",
                frameColor = "Gunmetal",
                lensType = "Smoke",
                gender = "Men",
                images = listOf("https://www.tomford.com/dw/image/v2/BCZV_PRD/on/demandware.static/-/Sites-master-catalog-tf/default/dw111/images/hi-res/FT0678_08A_A.jpg"),
                stock = 7,
                rating = 4.7,
                reviewCount = 10
            ),
            Product(
                id = "rb-erika-01",
                name = "Erika Classic",
                brand = "Ray-Ban",
                description = "Ray-Ban Erika RB4171 sunglasses are the perfect accessory to complete any look.",
                price = 147.0,
                originalPrice = 170.0,
                category = "Sunglasses",
                frameShape = "Round",
                frameMaterial = "Nylon",
                frameColor = "Rubber Black",
                lensType = "Gray Gradient",
                gender = "Women",
                images = listOf("https://images.ray-ban.com/is/image/RayBan/805289742463__002.png"),
                stock = 45,
                rating = 4.8,
                reviewCount = 420
            ),
            Product(
                id = "ok-latch-01",
                name = "Latch",
                brand = "Oakley",
                description = "A creative collaboration from the world of skateboarding, this design inspired by influential athletes is shaped with a classic keyhole bridge.",
                price = 150.0,
                originalPrice = 180.0,
                category = "Sunglasses",
                frameShape = "Round",
                frameMaterial = "O Matter",
                frameColor = "Matte Black",
                lensType = "Prizm Black",
                gender = "Unisex",
                images = listOf("https://assets.oakley.com/is/image/Oakley/888392100250__001.png"),
                stock = 18,
                rating = 4.7,
                reviewCount = 135
            ),
            Product(
                id = "cr-champion-01",
                name = "Champion/N",
                brand = "Carrera",
                description = "One of Carrera's most iconic shapes, the Champion/N is a modern take on the classic aviator with a focus on durability.",
                price = 120.0,
                originalPrice = 150.0,
                category = "Sunglasses",
                frameShape = "Aviator",
                frameMaterial = "Optyl",
                frameColor = "Black/Red",
                lensType = "Dark Gray",
                gender = "Unisex",
                images = listOf("https://www.carreraworld.com/media/catalog/product/c/a/carrera_champion_n_807_hd_01.png"),
                stock = 28,
                rating = 4.6,
                reviewCount = 90
            ),
            Product(
                id = "gc-rect-01",
                name = "Rectangular-Frame Metal",
                brand = "Gucci",
                description = "Retro-inspired rectangular frames in lightweight metal, accented with the Interlocking G on the temples.",
                price = 390.0,
                originalPrice = 480.0,
                category = "Luxury",
                frameShape = "Rectangular",
                frameMaterial = "Metal",
                frameColor = "Ruthenium",
                lensType = "Clear with Blue Light Filter",
                gender = "Unisex",
                images = listOf("https://media.gucci.com/style/DarkGray_Center_0_0_800x800/1550162104/561726_I3330_8131_001_100_0000_Light-Rect-frame-metal.jpg"),
                stock = 11,
                rating = 4.7,
                reviewCount = 18
            ),
            Product(
                id = "tf-snow-01",
                name = "Snow Goggles",
                brand = "Tom Ford",
                description = "High-performance snow goggles that don't sacrifice style. Features anti-fog lenses and plush triple-layer foam.",
                price = 595.0,
                originalPrice = 750.0,
                category = "Sports",
                frameShape = "Goggle",
                frameMaterial = "Flexible TPU",
                frameColor = "Black/Gold",
                lensType = "Photochromic",
                gender = "Unisex",
                images = listOf("https://www.tomford.com/dw/image/v2/BCZV_PRD/on/demandware.static/-/Sites-master-catalog-tf/default/dw1234/images/hi-res/FT0832_01A_A.jpg"),
                stock = 5,
                rating = 4.9,
                reviewCount = 5
            ),
            Product(
                id = "rb-justin-01",
                name = "Justin Classic",
                brand = "Ray-Ban",
                description = "Inspired by the iconic Wayfarer sunglasses, the Justin is one of the coolest looks in the Ray-Ban collection.",
                price = 140.0,
                originalPrice = 165.0,
                category = "Sunglasses",
                frameShape = "Square",
                frameMaterial = "Nylon",
                frameColor = "Rubber Gray",
                lensType = "Silver Mirror",
                gender = "Unisex",
                images = listOf("https://images.ray-ban.com/is/image/RayBan/805367206413__002.png"),
                stock = 50,
                rating = 4.8,
                reviewCount = 650
            )
        )

        val categories = listOf(
            com.opticalshop.data.model.Category(id = "cat-sun", name = "Sunglasses", order = 1),
            com.opticalshop.data.model.Category(id = "cat-luxury", name = "Luxury", order = 2),
            com.opticalshop.data.model.Category(id = "cat-sports", name = "Sports", order = 3),
            com.opticalshop.data.model.Category(id = "cat-computer", name = "Computer", order = 4)
        )

        CoroutineScope(Dispatchers.IO).launch {
            categories.forEach { category ->
                try { firestoreService.addCategory(category) } catch (e: Exception) { e.printStackTrace() }
            }
            products.forEach { product ->
                try {
                    firestoreService.addProduct(product)
                } catch (e: Exception) {
                    e.printStackTrace()
                }
            }
        }
    }
}
